#!/bin/sh

# Swap two files
swap() {
    local TMPFILE=tmp.$$
    mv "$1" $TMPFILE
    mv "$2" "$1"
    mv $TMPFILE "$2"
}

# Search man page
sman() {
    LESS="+/$2"
    man $1
}

# Print a glyph from font
glyph() { echo -e '\uE'$1; }

# Create a directory and cd into it
mkcd() { mkdir "$1" && cd "$1"; }

# Compile a .java and run the .class
javar() { javac "$1" && java $(basename "$1" .java) && rm *.class; }

# cd into a directory and show files
cl() {
    if [ $# -eq 1 ]; then
        cd "$1" && ls
    elif [ $# -eq 2 ]; then
        cd "$2" && ls "$1"
    fi
}

# Autojump (j) into a directory and show files
jl() {
    if [ $# -eq 1 ]; then
        j "$1" && ls
    elif [ $# -eq 2 ]; then
        j "$2" && ls "$1"
    fi
}

# Look for something in cat output
cag() { highlight -O ansi "$1" | grep -i "$2"; }

# Extract an archive
extract() {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
