#!/bin/bash

source /home/joe/.config/bspwm/panel/panel_config

FONT="-*-Uushi-*-*-*--10-*-*-*-*-*-*-*"
PAD='  '
ACT='onstart=uncollapse;button1=exit;button3=exit'
YPOS='32'
XPOS='1108'
TIME='3'

# Colors
FG="#$BAR_FG"
BG="#$BAR_BG"

bar_bg="$BAR_FG"
bar_fg="#$FOCUS_DESK"
label="#073642"
highlight="#002b36"
highlight2="#eee8d5"
warn="#cb4b16"

OPTIONS="-bg ${BG} -fg ${FG} -y ${YPOS} -x ${XPOS} -e ${ACT} -ta 'c'"
