#!/bin/bash
# Edited for February 2015 desktop. See panel config and termcolors.

FONT="-*-Uushi-*-*-*--11-*-*-*-*-*-*-*"
PAD='  '
ACT='onstart=uncollapse;button1=exit;button3=exit'
YPOS='20'
XPOS='1100'
TIME='3'

# Colors
FG="#c0b18b"
BG="#262626"

bar_bg="#c0b18b"
bar_fg="#3d9970"
label="#073642"
highlight="#002b36"
highlight2="#eee8d5"
warn="#cb4b16"

OPTIONS="-bg ${BG} -fg ${FG} -y ${YPOS} -x ${XPOS} -e ${ACT} -ta 'c'"

