#! /bin/sh

NORMIFS=$IFS
FIELDIFS=':'

source $(dirname $0)/panel_config

while read -r line ; do
    case $line in
        S*)
            sys_infos="${line#?}"
            ;;
        T*)
            title=$(echo ${line#?} | sed 's^\(.\{80\}\).*^\1...^')
            ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFf]*)
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F#FF3d9970}■%{F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F#FF3d9970}■%{F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F#FFc0b18b}■%{F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F#FFc0b18b}□%{F-}"
                                ;;
                        esac
                        wm_infos="${wm_infos}%{A:bspc desktop -f ${name}:}${PAD}${desk}${PAD}%{A}"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    printf "%s\n" "%{l #FFc0b18b} %{F#FF0074D9}%{F-} $wm_infos %{F#FFc0b18b B-}%{F-} %{c}${title} %{r}$sys_infos%{B-}"
done
