#! /bin/sh

source /home/joe/.config/global.conf

NORMIFS=$IFS
FIELDIFS=':'

while read -r line ; do
    case $line in
        S*)
            sys_infos="${line#?}"
            ;;
        T*)
            title=$(echo ${line#?} | sed 's^\(.\{80\}\).*^\1...^')
            ;;
        W*)
            wm_infos=""
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFf]*)
                        name=${item#?}
                        case $item in
                            O*)
                                # focused occupied desktop
                                desk="%{F#FF${MAIN_COLOR#\#}}%{F-}"
                                ;;
                            F*)
                                # focused free desktop
                                desk="%{F#FF${MAIN_COLOR#\#}}%{F-}"
                                ;;
                            o*)
                                # occupied desktop
                                desk="%{F#FF${BAR_FOREGROUND#\#}}%{F-}"
                                ;;
                            f*)
                                # free desktop
                                desk="%{F#FF${BAR_FOREGROUND#\#}}%{F-}"
                                ;;
                        esac
                        wm_infos="$wm_infos %{A:bspc desktop -f $name:} $desk %{A}"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac
    #printf "%s\n" " %{F#FF0074d9}%{F-}$wm_infos %{c}${title} %{r}$sys_infos%{B-}"
    printf "%s\n" " %{F#FF0074d9}%{F-}  $title %{c}$wm_infos  %{r}$sys_infos%{B-}"
done
