#!/bin/sh

source ~/.config/global.conf

ESSID() {
    ESSID="%{F#FF$BLACK}$(iwconfig wlp1s0 | grep ESSID | cut -d ":" -f 2 | tr -d "\" ")%{F-}"

    if [[ $(ps -e | grep shadow) ]]; then
        ICON="%{F#FF$BLACK}%{F-}"
        BG=$GREEN
    elif [ $ESSID = "off/any" ]; then
        ICON="%{F#FF$BLACK}%{F-}"
        ESSID="%{F#FF$BLACK}None%{F-}"
        BG=$BLUE
    else
        ICON="%{F#FF$BLACK}%{F-}"
        BG=$BLUE
    fi

    echo "%{B#FF$BG} $ICON $ESSID %{B-}"
}

Volume() {
    STATUS=$(volume status | cut -d " " -f 1)
    VOLUME="%{F#FF$BLACK}$(volume status | cut -d " " -f 2)%%%{F-}"

    if [[ $STATUS == "on" ]]; then
        if [[ $VOLUME > 40 ]]; then
            ICON="%{F#FF$BLACK}%{F-}"
            BG=$BLUE
        else
            ICON="%{F#FF$BLACK}%{F-}"
            BG=$BLUE
        fi
    else
        ICON="%{F#FF$BLACK}%{F-}"
        BG=$RED
    fi

    echo "%{B#FF$BG} $ICON $VOLUME %{B-}"
}

Battery() {
    STATUS=$(acpi | cut -d " " -f 3 | tr -d ",")
    PERCENT="%{F#FF$BLACK}$(acpi | cut -d " " -f 4 | tr -d "%,")%%%{F-}"

    if [[ $STATUS == "Charging" || $STATUS == "Full" ]]; then
        ICON="%{F#FF$BLACK}%{F-}"
        BG=$GREEN
    else
        if [[ $PERCENT > 69 ]]; then
            ICON="%{F#FF$BLACK}%{F-}"
            BG=$BLUE
        elif [[ $PERCENT < 70  && $PERCENT > 30 ]]; then
            ICON="%{F#FF$BLACK}%{F-}"
            BG=$BLUE
        else
            ICON="%{F#FF$BLACK}%{F-}"
            BG=$RED
        fi
    fi

    echo "%{B#FF$BG} $ICON $PERCENT %{B-}"
}

Time() {
    ICON="%{F#FF$BLACK}%{F-}"
    DATE="%{F#FF$BLACK}$(date +"%a %-I:%M %p")%{F-}"

    echo "%{B#FF$BLUE} $ICON $DATE %{B-}"
}

Pacman() {
    ICON="%{F#FF$BLACK}%{F-}"
    UPDATES="%{F#FF$BLACK}$(ls / | wc -l)%{F-}"

    if [[ $UPDATES == 1 ]]; then
        echo "%{B#FF$YELLOW} $ICON $UPDATES %{F#FF$BLACK}update%{F-} %{B-}"
    elif [[ $UPDATES > 1 ]]; then
        echo "%{B#FF$YELLOW} $ICON $UPDATES %{F#FF$BLACK}updates%{F-} %{B-}"
    fi
}

Temp() {
    TEMP="%{F#FF$BLACK}$(acpi -t -f | cut -d " " -f 4)%{F-}"
    ICON="%{F#FF$BLACK}%{F-}"

    if [[ $TEMP > 130 ]]; then
        echo "%{B#FF$RED} $ICON $TEMP %{B-}"
    else
        exit
    fi
}

while :; do
    echo "S  $(Pacman)$(Temp)$(ESSID)$(Volume)$(Battery)$(Time) %{A}"
    sleep 1
done
