#!/bin/sh

source /home/joe/.config/colors/global.conf

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e $PANEL_FIFO ] && rm $PANEL_FIFO
mkfifo $PANEL_FIFO

bspc control --subscribe > $PANEL_FIFO &

xtitle -sf 'T%s' > $PANEL_FIFO &
conky -c ~/.config/conky/panel_conky > $PANEL_FIFO &

~/.config/bspwm/panel/bar < $PANEL_FIFO \
     | bar -p \
           -g $BAR_GEOMETRY \
           -f $FONT1,$FONT2,$FONT3 \
           -B "#FF${BAR_BACKGROUND#\#}" \
           -F "#FF${BAR_FOREGROUND#\#}" \
           | while read line; do eval "$line"; done &
wait

