#!/bin/sh

source ~/.config/global.conf

ESSID() {
    ESSID=$(iwconfig wlp1s0 | grep ESSID | cut -d ":" -f 2 | tr -d "\"")

    if [[ $(ps -e | grep shadow) ]]; then
        ICON="%{F#FF$GREEN}%{F-}"
    elif [ $ESSID = "off/any" ]; then
        ICON="%{F#FF$MAIN_COLOR}%{F-}"
        ESSID="None"
    else
        ICON="%{F#FF$MAIN_COLOR}%{F-}"
    fi

    echo $ICON $ESSID
}

Volume() {
    STATUS=$(volume status | cut -d " " -f 1)
    VOLUME=$(volume status | cut -d " " -f 2)%%

    if [[ $STATUS == "on" ]]; then
        if [[ $VOLUME > 40 ]]; then
            ICON="%{F#FF$MAIN_COLOR}%{F-}"
        else
            ICON="%{F#FF$MAIN_COLOR}%{F-}"
        fi
    else
        ICON="%{F#FF$RED}%{F-}"
    fi

    echo $ICON $VOLUME
}

Battery() {
    STATUS=$(acpi | cut -d " " -f 3 | tr -d ",")
    PERCENT=$(acpi | cut -d " " -f 4 | tr -d "%,")%%

    if [[ $STATUS == "Charging" || $STATUS == "Full" ]]; then
        ICON="%{F#FF$GREEN}%{F-}"
    else
        if [[ $PERCENT > 69 ]]; then
            ICON="%{F#FF$MAIN_COLOR}%{F-}"
        elif [[ $PERCENT < 70  && $PERCENT > 30 ]]; then
            ICON="%{F#FF$MAIN_COLOR}%{F-}"
        else
            ICON="%{F#FF$RED}%{F-}"
        fi
    fi

    echo $ICON $PERCENT
}

Time() {
    ICON="%{F#FF$BLACK}%{F-}"
    DATE="%{F#FF$BLACK}$(date +"%a %-I:%M %p")%{F-}"

    echo "%{B#FF$MAIN_COLOR} $ICON $DATE %{B-}"
}

Pacman() {
    ICON="%{F#FF$YELLOW}%{F-}"
    UPDATES=$(pacman -Qqu | wc -l)

    if [[ $UPDATES == 1 ]]; then
        echo $ICON $UPDATES update
    elif [[ $UPDATES > 1 ]]; then
        echo $ICON $UPDATES updates
    fi
}

Temp() {
    TEMP=$(acpi -t -f | cut -d " " -f 4)
    ICON="%{F#FF$RED}%{F-}"

    if [[ $TEMP > 130 ]]; then
        echo "  $ICON $TEMP"
    else
        exit
    fi
}

while :; do
    echo "S  $(Pacman)$(Temp)  $(ESSID)  $(Volume)  $(Battery)  $(Time)%{A}"
    sleep 1
done
