#!/bin/sh

source ~/.config/global.conf

ESSID() {
    ICON="%{F#FF$MAIN_COLOR}%{F-}"
    ESSID=$(iwconfig wlp1s0 | grep ESSID | cut -d ":" -f 2 | tr -d "\"")

    echo $ICON $ESSID
}

Volume() {
    STATUS=$(volume status | cut -d " " -f 1)
    VOLUME=$(volume status | cut -d " " -f 2)%%

    if [[ $STATUS == "on" ]]; then
        ICON="%{F#FF$MAIN_COLOR}%{F-}"
    else
        ICON="%{F#FF$RED}%{F-}"
    fi

    echo $ICON $VOLUME
}

Battery() {
    STATUS=$(acpi | cut -d " " -f 3 | tr -d ",")
    PERCENT=$(acpi | cut -d " " -f 4 | tr -d "%,")%%

    if [[ $STATUS == "Charging" || $STATUS == "Full" ]]; then
        ICON="%{F#FF$GREEN}%{F-}"
    else
        if [[ $PERCENT > 69 ]]; then
            ICON="%{F#FF$MAIN_COLOR}%{F-}"
        elif [[ $PERCENT < 70  && $PERCENT > 40 ]]; then
            ICON="%{F#FF$MAIN_COLOR}%{F-}"
        else
            ICON="%{F#FF$RED}%{F-}"
        fi
    fi

    echo $ICON $PERCENT
}

Time() {
    ICON="%{F#FF$MAIN_COLOR}%{F-}"
    DATE=$(date +"%A %b %d %-I:%M %p")

    echo $ICON $DATE
}

Pacman() {
    ICON="%{F#FF$YELLOW}%{F-}"
    UPDATES=$(pacman -Qu | wc -l)

    if [[ $UPDATES > 0 ]]; then
        echo $ICON $UPDATES updates
    fi
}

Weather() {
    if [[ $LOCATION == "" ]]; then
        return
    fi

    ICON="%{F#FF$MAIN_COLOR}%{F-}"
    WEATHER=$(weather "$LOCATION" --iconify)

    echo $ICON $WEATHER\
}

while :; do
    echo "S $(Pacman)  $(Weather)  $(ESSID)  $(Volume)  $(Battery)  $(Time) %{B}"
    sleep 1
done
