#!/bin/sh

source ~/.config/global.conf

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e $PANEL_FIFO ] && rm $PANEL_FIFO
mkfifo $PANEL_FIFO

bspc control --subscribe > $PANEL_FIFO &

xtitle -sf 'T%s' > $PANEL_FIFO &
~/.config/bspwm/panel/panel_stats > $PANEL_FIFO &

~/.config/bspwm/panel/panel_bar < $PANEL_FIFO \
     | lemonbar -p \
           -g $BAR_GEOMETRY \
           -f $FONT1 \
           -f $FONT2 \
           -B "#FF$BAR_BACKGROUND" \
           -F "#FF$BAR_FOREGROUND" \
           | while read line; do eval "$line"; done &
wait
