format = """
$all\
$kubernetes\
$custom\
$fill\
$battery\
$cmd_duration\
$time\
$line_break\
$prompt\
$jobs\
$shell\
$character\
"""
right_format = "$status"
command_timeout = 1500

[fill]
symbol = " "

[character]
vicmd_symbol = "[❮](bold blue)"
# vicmd_replace_symbol = "[❮](bold red)"
# vicmd_visual_symbol = "[❮](bold orange)"

[username]
# show_always = true
format = "[$user]($style) in "

[hostname]
# ssh_only = false
style = "bold dimmed purple"
format = " at [$hostname]($style) "

[jobs]
style = "bold yellow"
symbol = "▥"

[time]
disabled = false
style = "bold dimmed yellow"
format = "[$time]($style) "
time_format = "%_I:%M %P"

[status]
disabled = false
map_symbol = true
not_executable_symbol = "+x "
sigint_symbol = "^C "
not_found_symbol = "? "
signal_symbol = " "
symbol = "✖ "
format = "[$symbol$status]($style)"

[directory]
format = "in [$path]($style)[$read_only]($read_only_style) "
read_only = "  "
truncation_length = 4

[cmd_duration]
format = "took [$duration]($style) "

[git_branch]
symbol = " "

# [git_status]
# disabled = true

# [git_metrics]
# disabled = false

# [fossil_branch]
# disabled = false

[kubernetes]
format = '⛴️  [$context](bold blue) [$namespace](dimmed green)'
disabled = false

  [kubernetes.context_aliases]
  "gke_saas-(\\w+-){3,}(?P<project_id>[^_]+)_(?P<region>[^_]+)_(?P<cluster>[^_]+)" = "$cluster $project_id"

[helm]
symbol = "☸️  "
disabled = true

[gcloud]
format = "via [$symbol$account]($style) "
disabled = true

[package]
symbol = ""
format = "on [$symbol$version]($style) "
# disabled = true

# [custom.argocd]
# command = "argocd context | grep '*' | awk '{print $2}'"
# when = "grep -q '*' <(argocd context)"
# format = "[$output](dimmed yellow) "
