right_format = "$status$time"

[character]
vicmd_symbol = "[❮](bold blue)"

[username]
# show_always = true
format = "[$user]($style) on "

[hostname]
# ssh_only = true
style = "bold dimmed purple"

[jobs]
style = "bold blue"
symbol = "+"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%_I:%M %P"

[status]
disabled = false
symbol = "✖ "

[directory]
format = "[$path]($style) [$read_only]($read_only_style)"
