# Dell XPS 13 DRI 2
export LIBGL_DRI3_DISABLE=1

# Terminal
export TERM=xterm-256color

# Path
CARGOPATH="$HOME/.cargo/bin"

export PATH="${PATH}:${CARGOPATH}"

# Editor
[ "$(command -v nvim)" ] && export EDITOR=nvim || export EDITOR=vim

# FZF
export FZF_DEFAULT_COMMAND="rg --files --hidden -g '!{node_modules,.git,.venv,.env}'"
export FZF_DEFAULT_OPTS="--height 50% --layout=reverse"

# Pager
export PAGER=less

# Ctrl-W backspace word
export WORDCHARS=""

export LC_COLLATE="C"

export NNN_FIFO="/tmp/nnn.fifo"
export NNN_PLUG="p:preview-tui"
