# Disable DRI3 (xps 13 9510)
# export LIBGL_DRI3_DISABLE=1

# Terminal
export TERM=xterm-256color

# Path
CARGOPATH="$HOME/.cargo/bin"

export PYENVROOT="$HOME/.pyenv"
PYENVPATH="$PYENVROOT/bin"

export PATH="${PATH}:${CARGOPATH}:${PYENVPATH}"

eval "$(pyenv init --path)"

# Editor
[ "$(command -v nvim)" ] && export EDITOR=nvim || export EDITOR=vim

# Lang
export LC_ALL="en_US.UTF-8"

# Pager
export PAGER=less

# Ctrl-W backspace word
export WORDCHARS=""

# FZF
export FZF_DEFAULT_COMMAND="rg --files --hidden -g '!{node_modules,.git,.venv,.env}'"
export FZF_DEFAULT_OPTS="--height 50% --layout=reverse"

# Vi-mode
export ZVM_CURSOR_STYLE_ENABLED=false
export KEYTIMEOUT=1

# Java
export _JAVA_AWT_WM_NONREPARENTING=1

# Qt
export QT_QPA_PLATFORMTHEME=gtk2
