#!/bin/sh

bspc monitor -d 1 2 3 4 5

bspc config top_padding             0
bspc config border_width            4
bspc config window_gap              8

bspc config split_ratio             0.55

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config single_monocle          true

bspc config normal_border_color     "#181818"
bspc config focused_border_color    "#7cafc2"

bspc rule -a Thunar state=floating
bspc rule -a feh state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Gpa state=floating rectangle=1010x750
bspc rule -a lxappearance state=floating
bspc rule -a Audacity state=floating
bspc rule -a polybar layer=above
bspc rule -a Dunst layer=above sticky=on private=on
bspc rule -a Alacritty layer=normal rectangle=1300x740+310+200
bspc rule -a "Alacritty:*:Scratch" state=floating sticky=on locked=on private=on border=off hidden=on focus=on layer=above rectangle=1920x540+0+0
bspc rule -a "firefox:*:Picture-in-Picture" state=floating sticky=on locked=on private=on border=off focus=on layer=above rectangle=633x396+1279+736

$HOME/.config/polybar/launch.sh
polybar=$(xdo id -N Polybar)

bspc subscribe node | while read -r event _ _ node state status; do
    echo $event $node $state $status

    if [[ $state == "fullscreen" ]]; then
        case "$status" in
            on)
                bspc node $polybar -t layer=below
                xdo lower $polybar
                ;;
            off)
                bspc node $polybar -t layer=above
                xdo raise $polybar
                ;;
        esac
    fi

    if [[ $state == "move" && $status == "end" && $(wname $node) == "Scratch" ]]; then
        xdotool windowmove $node 0 0
    fi

    if [[ $state == "resize_corner" && $status == "end" && $(wname $node) == "Scratch" ]]; then
        xdotool windowsize $node 1920 540
    fi

done &
