#!/bin/sh

bspc config border_width            2
bspc config top_padding             13
bspc config window_gap              5
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config focused_border_color    "#ff4136"
bspc config urgent_border_color     "#f92672"

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp floating=on

amixer sset Headphone 100
amixer sset Master 0

xset m 5/3
xsetroot -cursor_name left_ptr

xrdb ~/.Xresources &
unclutter -idle 3 &
compton -b --config ~/.config/compton/comptonrc &
redshift -l 30:-81 -t 6400:4400 &

~/.config/scripts/bspwm_panel.sh &
