#!/usr/bin/env bash

function get_brightness {
    xbacklight -get | cut -d '.' -f 1
}

function send_notification {
    brightness=$(get_brightness)
    bar=$(seq -s "─" 0 $((brightness / 3)) | sed 's/[0-9]//g')
    dunstify -u low -t 1500 -r 5555 "  $bar"
}

case $1 in
    up)
        # increase the backlight by 5%
        xbacklight -inc 5 -time 0
        send_notification
        ;;
    down)
        # decrease the backlight by 5%
        xbacklight -dec 5 -time 0
        send_notification
        ;;
esac
