#!/usr/bin/env bash

function get_volume {
    pactl list sinks | grep '^[[:space:]]Volume:' | \
        head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

function send_notification {
    volume=$(get_volume)
    bar=$(seq --separator="─" 0 "$((volume / 3))" | sed 's/[0-9]//g')

    if [ $volume -ge 49 ]; then
        dunstify -u low -t 1500 -r 2593 "  $bar"
    elif [ $volume -lt 49 ]; then
        dunstify -u low -t 1500 -r 2593 "  $bar"
    fi
}

case $1 in
    up)
        amixer -D pulse set Master on > /dev/null
        amixer -D pulse sset Master 5%+ > /dev/null
        send_notification
        ;;
    down)
        amixer -D pulse set Master on > /dev/null
        amixer -D pulse sset Master 5%- > /dev/null
        send_notification
        ;;
esac
