#!/bin/zsh

if [ ! -f ${ADOTDIR}/antigen.zsh ]; then
  mkdir -p ${ADOTDIR}
  curl -s -L git.io/antigen > ${ADOTDIR}/antigen.zsh
fi

source ${ADOTDIR}/antigen.zsh

antigen bundles <<EOF
  zdharma-continuum/fast-syntax-highlighting
  zsh-users/zsh-history-substring-search
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions
  le0me55i/zsh-extract
  mdumitru/fancy-ctrl-z
  jeffreytse/zsh-vi-mode
  ael-code/zsh-colored-man-pages
  trapd00r/LS_COLORS
  rupa/z

  # omz
  common-aliases
  docker
  git
  gitfast
  git-flow-avh
  git-extras
  git-auto-fetch
  gitignore
  kubectl
  ripgrep
EOF

antigen apply

# Zstyles
zstyle ":completion:*" menu select

zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'

zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

# Autcomplete
autoload -Uz compinit && compinit -u
zmodload zsh/complist

# Keybindings
bindkey '^ ' autosuggest-execute

bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down
bindkey -a "k" history-substring-search-up
bindkey -a "j" history-substring-search-down

bindkey "^?" backward-delete-char
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

bindkey -M menuselect '^[[Z' reverse-menu-complete

# History
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=$HOME/.zsh_history

# Options
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups

setopt append_history
setopt extended_history
setopt inc_append_history
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt hist_ignore_space
setopt hist_verify

setopt auto_menu
setopt complete_in_word
setopt always_to_end
setopt bad_pattern
setopt extended_glob
setopt interactive_comments
setopt auto_continue
setopt mark_dirs
setopt bang_hist

source /etc/zsh/zaliases

[ "$(command -v pyenv)" ] && eval "$(pyenv init -)"
[ "$(command -v starship)" ] && eval "$(starship init zsh)"
[ "$(command -v cog)" ] && eval $(cog generate-completions zsh)
