#!/bin/zsh

if [ ! -f ${ADOTDIR}/antigen.zsh ]; then
  mkdir -p ${ADOTDIR}
  curl -s -L git.io/antigen > ${ADOTDIR}/antigen.zsh
fi

source ${ADOTDIR}/antigen.zsh

antigen bundles <<EOF
  zdharma-continuum/fast-syntax-highlighting
  zsh-users/zsh-history-substring-search
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-completions
  le0me55i/zsh-extract
  mdumitru/fancy-ctrl-z
  jeffreytse/zsh-vi-mode
  ael-code/zsh-colored-man-pages
  trapd00r/LS_COLORS
  rupa/z

  common-aliases
  docker
  git
  gitfast
  git-flow-avh
  git-extras
  git-auto-fetch
  gitignore
  ripgrep
  helm
  gcloud
  pyenv
  kubectl
EOF

antigen apply

# Zstyles
zstyle ":completion:*" menu select

zstyle ':completion:*' matcher-list '' \
  'm:{a-z\-}={A-Z\_}' \
  'r:[^[:alpha:]]||[[:alpha:]]=** r:|=* m:{a-z\-}={A-Z\_}' \
  'r:|?=** m:{a-z\-}={A-Z\_}'

zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

zstyle ':completion:*:*:docker:*' option-stacking yes
zstyle ':completion:*:*:docker-*:*' option-stacking yes

zle_highlight=('paste:none')

# Autcomplete
fpath+=(/opt/homebrew/share/zsh/site-functions)
compdef kubecolor='kubectl'

autoload -Uz compinit && compinit
zmodload zsh/complist

# Keybinds
function zvm_after_init() {
  zvm_bindkey viins '^ ' autosuggest-execute

  zvm_bindkey viins "^[[A" history-substring-search-up
  zvm_bindkey viins "^[[B" history-substring-search-down
  zvm_bindkey viins "^[[1;5C" forward-word
  zvm_bindkey viins "^[[1;5D" backward-word

  zvm_bindkey viins "^?" backward-delete-char
  zvm_bindkey viins "^Z" fancy-ctrl-z
}

bindkey -a "k" history-substring-search-up
bindkey -a "j" history-substring-search-down

bindkey -M menuselect '^[[Z' reverse-menu-complete

# History
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=$HOME/.zsh_history

# Options
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups

setopt append_history
setopt extended_history
setopt inc_append_history
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt hist_ignore_space
setopt hist_verify

setopt auto_menu
setopt complete_in_word
setopt always_to_end
setopt bad_pattern
setopt extended_glob
setopt interactive_comments
setopt auto_continue
setopt mark_dirs
setopt bang_hist

source "$HOME/.zsh_aliases"

[ "$(command -v starship)" ] && eval "$(starship init zsh)"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /opt/homebrew/bin/terraform terraform
