# available tags:
#   <city>
#   <icon>
#   <temperature>                   Celsius/Fahrenheit/Kelvin
#   <temperature_feels_like>        Celsius/Fahrenheit/Kelvin
#   <temperature_max>               Celsius/Fahrenheit/Kelvin
#   <temperature_min>               Celsius/Fahrenheit/Kelvin
#   <dew_point>                     Celsius/Fahrenheit/Kelvin
#   <precipitation>                 Millimeter/Inch
#   <precipitation_chance>          Percentage
#   <clouds>                        Percentage
#   <humidity>                      Percentage
#   <visibility>                    Meter/Kilometer/Mile
#   <wind_speed>                    Ms/Kmh/Mph
#   <pressure>                      Hpa
#   <uv_index>                      Integer
#   <air_quality_index>             Integer
#   <sunrise>                       H:M
#   <sunset>                        H:M

format = '<icon>  <temperature>°F'
interval = 300

[units]
temperature = 'Fahrenheit'
wind_speed = 'Mph'
distance = 'Mile'
precipitation = 'Inch'

[weather]
provider = 'OpenWeatherMap'
api_key = ''

[location]
# available providers:
#   IpApi
#   Manual
# default: IpApi

provider = 'IpApi'
#lat = 51.509865
#lon = -0.118092

[icons]
clear_sky = ''
few_clouds = ''
clouds = ''
many_clouds = ''
rain = ''
heavy_rain = ''
thunderstorm = ''
snow = ''
mist = ''
